# Generated by Django 3.2.25 on 2026-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260311_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_mileage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='chain_lube_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chain_lube_kms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='engine_cc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_oil_service_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_oil_service_kms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='major_service_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major_service_kms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tyre_change_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tyre_change_kms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
